name: Test
on:
  - pull_request
  - push
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v13
      - run: nix-shell --pure --run "go test -v -race ./..."
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v13
      - run: nix-shell --pure --run "golangci-lint run --timeout 15m"
  integration:
    needs:
      - unit
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v13
      - run: nix-shell --pure --run "go test ./... -tags suite"
